const Hotel = [
  {
    id: 1,
    house: "./villa_images/House/villa1.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
  {
    id: 2,
    house: "./villa_images/House/villa2.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
  {
    id: 3,
    house: "./villa_images/House/villa3.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
  {
    id: 4,
    house: "./villa_images/House/villa4.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
  {
    id: 5,
    house: "./villa_images/House/villa6.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
  {
    id: 6,
    house: "./villa_images/House/villa7.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
  {
    id: 7,
    house: "./villa_images/House/villa8.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
  {
    id: 8,
    house: "./villa_images/House/villa10.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
  {
    id: 9,
    house: "./villa_images/House/villa11.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
  {
    id: 10,
    house: "./villa_images/House/villa12.jpg",
    iconss: "./villa_images/images.jpg",
    name: "Barbeque Nation",
    rate: "3.9",
    time: "65-70 mins",
    more: "Barbeque,Biryani,Kebabs,...",
    location: "Dhankawadi",
  },
];

export default Hotel;
